# Generated by Django 5.2.3 on 2025-06-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
