# Generated by Django 5.2.3 on 2025-06-29 18:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_brand_slug_category_slug_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
