# Generated by Django 5.2.3 on 2025-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_how_to_use_product_ingredients_productshade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_shades/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_variants/'),
        ),
    ]
