# Generated by Django 5.2.3 on 2025-07-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productshade_image_productvariant_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set(),
        ),
    ]
