# Generated by Django 5.2.3 on 2025-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_productimage_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="productshade",
            name="sku",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="SKU"
            ),
        ),
        migrations.AddField(
            model_name="productshade",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
