version: "1.1"

services:
  web:
    build: .
    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 80:8000
    environment:
      - ENVIRONMENT=staging
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:postgres@web-db:5432/web_dev
      - PORT=8000
      - PGHOST=localhost
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=ew
    network_mode: "host"