# Generated by Django 5.2.3 on 2025-07-04 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem"),
        ("product", "0004_alter_productimage_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="selected_shade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productshade",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="selected_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={
                ("user", "product", "selected_shade"),
                ("user", "product", "selected_variant"),
            },
        ),
    ]
