# Generated by Django 5.0 on 2025-07-14 12:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="staff",
            name="bio",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
