# Generated by Django 5.0 on 2025-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_service_description_alter_staff_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[("beauty", "Beauty"), ("dermatology", "Dermatology")],
                default="beauty",
                max_length=20,
            ),
        ),
    ]
