# Generated by Django 5.2.3 on 2025-06-30 07:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
