# Generated by Django 5.2.3 on 2025-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_covers/"),
        ),
    ]
