# Generated by Django 5.2.3 on 2025-06-30 07:37

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog_sections/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
