# Generated by Django 5.2.3 on 2025-06-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Banner Title"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="banners/", verbose_name="Banner Image"
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="Banner Link"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["-id"],
            },
        ),
    ]
