# Generated by Django 5.2.3 on 2025-07-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0003_alter_banner_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Nav Item Title"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nav Item Link",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="siteconfig.navitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nav Item",
                "verbose_name_plural": "Nav Items",
                "ordering": ["-id"],
            },
        ),
    ]
