# Generated by Django 5.2.3 on 2025-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0004_navitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="navitem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
